### ISSUE TITLE
Replace API Key and secret 

### ISSUE THREAD

**Issue by RUBYJABER** [AppliedRecognition/Ver-ID-Android-Sample#2]
I couldn't run the application properly with my own key and secret ! may you help me please.
Regards,

**Comment by RUBYJABER** [comment]
its still working with the api secret that is existed on the project already
here is the name of the package : com.appliedrec.ver_idsample

**Comment by jakubdolejs** [comment]
Hi @RUBYJABER, I'm not sure I understand your question. Are you saying that the API secret for com.appliedrec.ver_idsample is working?

**Comment by RUBYJABER** [comment]
yeah its working, but you notice us that we have to replace it with our own API secret, but I couldn't have my own API.

Regards,
